config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'static_pages/about'
  get  'static_pages/contact'
  get  'static_pages/number'
  get  'static_pages/scraping'
  get  'comments/index'
  resources :posts

  namespace :api, format: 'json' do
    namespace :v1  do
      resources :comments
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @data = Comment.all
  end

  def create
    @comment = Comment.create(comment_params)
    render :show, status: :created
  end

  private

    def comment_params
      params.permit(:author, :text)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
#  protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def number
    logger.debug "出力したいデバッグ情報: " + params[:file_id]
    render file: "public/#{params[:file_id]}", layout: true, content_type: 'text/html'
  end

  def node
    logger.debug "出力したいデバッグ情報: " + params[:file_id]
    render file: "public/node/#{params[:file_id]}", layout: true, content_type: 'text/html'
  end

  include Scrape
  def scraping
    @url_scrapings = url_scraping
    logger.debug "出力したいデバッグ情報: " + @url_scrapings[0][0]
  end


end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/index.html.erb
<% provide(:title, "React Tutorial") %>
<div class="container">
  <div class="jumbotron">
    <div class="description_message"></div>
    <div class="workspace">
      <%= react_component('CommentBox', url: '/api/v1/comments.json', pollInterval: 2000) %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
    <div class="row">
        <!-- フッターは等分なしのワンカラム col-sm-12 -->
        <div class="col-sm-12">
          <footer>
            <p>© 2016 ShunKubota All rights reserved.</p>
          </footer>
        </div>
      </div>

app/views/layouts/_header.html.erb
  <!-- 雰囲気を出すためにナビバーも表示 -->
  <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="sr-only">navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Shun Kubota", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Blog", posts_path %></li>
          <li><%= mail_to "shun.ku60ta@gmail.com", "Contact", :cc => "", :subject => "From 200 websites in 200 days" %></li>
          <li><%= link_to "Github", "https://github.com/KuboShun/shun_kubota" , target: "_blank" %></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- ナビバー終了 -->

<!-- モーダル・ダイアログ -->
<div class="modal fade" id="sampleModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
        <h4 class="modal-title">タイトル</h4>
      </div>
      <div class="modal-body">
        本文
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        <button type="button" class="btn btn-primary">ボタン</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= yield(:title) %> | Shun Kubota</title>
  
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for :post, url: posts_path do |f| %>
  <div class="container">
    <div class="jumbotron">
      <div class="description_message">
        Blog
      </div>
      <div class="workspace">
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2>You got <%= pluralize(@post.errors.count, "error") %></h2>
            <ul>
              <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <h2><%= link_to "All Posts", posts_path %></h2>
          <%= f.text_field :title %>
          <%= f.text_area :description, cols: 60, rows: 8 %>
          <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title,"Edit Post") %>

<%= render "form" %>

app/views/posts/index.html.erb
<% provide(:title,"Blog") %>
<div class="container">
  <div class="jumbotron">
    <div class="description_message">
      All Posts
    </div>
    <div class="workspace">



      <button type="button" class="btn btn-default" id="modal-open">New Post</button>
      <div id="modal-main">
        <%= bootstrap_form_for :post, url: posts_path do |f| %>
          <%= f.text_field :title %>
          <%= f.text_area :description, cols: 60, rows: 8 %>
          <%= f.submit %>
        <% end %>
      </div>
 


      <table class="post_table">
        <tr>
          <th>TITLE</th>
          <th>Description</th>
          <th></th>
        </tr>

        <% @posts.each do |post| %>
          <tr>
            <td><%= truncate(post.title, :length => 40) %></td>
            <td><%= truncate(post.description, :length => 60) %></td>
            <td><%= link_to "Edit", edit_post_path(post), class: 'btn btn-primary btn-xs'%>  
                <%= link_to "Show", post, class: 'btn btn-primary btn-xs' %>  
                <%= link_to '削除', post_path(post), method: :delete, data: { confirm: '削除しますか？' }, class: "btn btn-danger btn-xs" %></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>


<script type="text/javascript">
  var modal_switch = false;
  $("#modal-main").css("display", "none");

  $("#modal-open").click(function(){
    console.log("a");
    if (!modal_switch) {
      $("#modal-main").fadeIn("slow");
      modal_switch = true;
      console.log("b");
    } else {
      $("#modal-main").fadeOut("slow");
      modal_switch = false;
      console.log("c");
    }
  });

</script>

app/views/posts/new.html.erb
<% provide(:title,"New Post") %>

<%= render "form" %>

app/views/posts/show.html.erb
<% provide(:title,"Blog") %>
<div class="container">
  <div class="jumbotron">
    <div class="description_message">
      Blog
    </div>
    <div class="workspace">
    <h2><%= link_to "All Posts", posts_path %></h2>
      <%= @post.inspect %><br />
      <%= @post.title %><br />
      <%= @post.description %>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title,"Shun Kubota") %>
  <div class="container">
    <div class="jumbotron">
      <h2 style="font-family:futura; font-weight:900">I taught myself to code by making 200 websites in 200 days!</h2>
      <p>From July 4, which is my birthday, 2016 to January 20, 2017, I make one website a day, every single day as a learn to code project. Along the way, I am going to publish all my code publicly on GitHub and wrote a blog post to accompany websites. I started with just a little html and css.</p>
    </div>
  </div>

app/views/static_pages/contact.html.erb
<% provide(:title,"Shun Kubota") %>
  <div class="container">
    <!-- 見出し -->
    <div class="jumbotron">
      <h1>200 websites in 200 days.</h1>
      <p>I'm Shun Kubota from Japan and I am making websites.<br />
         You can follow the project here.</p>
      <p><a href="" target="_blank" class="btn btn-success btn-lg">START</a></p>
    </div><!-- 見出し終了 -->
    <div class="row">
      
    </div>

    <div class="row">
      <!-- 大画面PCでは6等分（col-lg-2）、PC では3等分（col-md-4）、タブレットでは2等分（col-sm-6）、それ以下では等分なしのワンカラム・レイアウト -->
      <div class="col-sm-6 col-md-4 col-lg-4">
        <h2>HTML</h2>
        <p>HTML is a markup language that is used for creating web pages.</p>
        <p><a href="" target="_blank" class="btn btn-success">詳細 &raquo;</a></p>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-4">
        <h2>CSS</h2>
        <p>CSS is used for describing the presentation of web pages. </p>
        <p><a href="" target="_blank" class="btn btn-success">詳細 &raquo;</a></p>
      </div>
      <div class="clearfix visible-sm-block"></div>
        <div class="col-sm-6 col-md-4 col-lg-4">
          <h2>Bootstrap</h2>
        <p>Bootstrap is a powerful front-end framework for faster and easier web development. </p>
        <p><a href="" target="_blank" class="btn btn-success">詳細 &raquo;</a></p>
      </div>
      <div class="clearfix visible-md-block"></div>
        <hr>
        <div class="row">
          <!-- フッターは等分なしのワンカラム col-sm-12 -->
          <div class="col-sm-12">
            <footer>
              <p>© 2016 ShunKubota All rights reserved.</p>
            </footer>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/geocode.html.erb
<% provide(:title,"Geocode") %>
  <div class="container">
    <!-- 見出し -->
    <div class="jumbotron">
      <h1>Welcome!</h1>
      <h2 style="font-family:futura; font-weight:900">Geocode</h2>
      <hr>
      hogehoge

      <%= form_for(@location, url: nearby_locations_path, html: {method: "post"}) do |f| %>
        <%= f.hidden_field :latitude %>
        <%= f.hidden_field :longitude %>
        .actions
          <%= f.submit '現在地から近いレコードを検索' %>
          <% end %>
      <hr>

    </div><!-- 見出し終了 -->
  </div>

  <script type="text/javascript" src="/javascripts/geocode.js"></script>

app/views/static_pages/home.html.erb
<% provide(:title,"200 websites in 200 days") %>
  <div class="container">
    <div class="jumbotron">
      <h1>Welcome!</h1>
      <h2 style="font-family:futura; font-weight:900">200 websites in 200 days.</h2>
        <p>I'm Shun Kubota from Japan and I am making websites.<br />
         You can follow the project here.
        </p>
      <hr>
        <p><strong>Today's Website : 
        <span><%= link_to "BMI culculator", controller: "static_pages", action: "number", file_id: "bmi_culculator" %></span>
        </strong></p>
      <hr>


    </div>
    <div class="row">
      <div class="col-sm-6 col-md-4 col-lg-4 website_list_container">
        <div>Day 26 <span><%= link_to "BMI culculator", controller: "static_pages", action: "number", file_id: "bmi_culculator" %></span></div>
        <div>Day 25 <span><%= link_to "Countdown Timer", controller: "static_pages", action: "number", file_id: "countdown_timer" %></span></div>
        <div>Day 24 <span><%= link_to "React Timer", controller: "static_pages", action: "number", file_id: "helloworld" %></span></div>
        <div>Day 23 <span><%= link_to "Mindmap", controller: "static_pages", action: "number", file_id: "mindmap" %></span></div>
        <div>Day 22 <span><%= link_to "React memo(in maintenance)", controller: "comments" %></span></div>
        <div>Day 21 <span><%= link_to "Calculator", controller: "static_pages", action: "number", file_id: "calculator" %></span></div>
        <div>Day 20 <span><%= link_to "Balloon", controller: "static_pages", action: "number", file_id: "balloon" %></span></div>
        <div>Day 19 <span><%= link_to "Bound Ball", controller: "static_pages", action: "number", file_id: "bound_ball" %></span></div>
        <div>Day 18 <span><%= link_to "p5", controller: "static_pages", action: "number", file_id: "p5" %></span></div>
        <div>Day 17 <span><%= link_to "Audio Recorder", controller: "static_pages", action: "number", file_id: "audio_recorder" %></span></div>
        <div>Day 16 <span><%= link_to "Face Tracker", controller: "static_pages", action: "number", file_id: "face_tracker" %></span></div>
        <div>Day 15 <span><%= link_to "Make Balls", controller: "static_pages", action: "number", file_id: "make_balls" %></span></div>
        <div>Day 14 <span><%= link_to "Scraping", controller: "static_pages", action: "scraping" %></span></div>
        <div>Day 13 <span><%= link_to "Box Changer", controller: "static_pages", action: "number", file_id: "box_changer" %></span></div>
        <div>Day 12 <span><%= link_to "Party Organizer", controller: "static_pages", action: "number", file_id: "party_organizer" %></span></div>
        <div>Day 11 <span><%= link_to "Make Background", controller: "static_pages", action: "number", file_id: "make_background" %></span></div>
        <div>Day 10 <span><%= link_to "Name Plate", controller: "static_pages", action: "number", file_id: "name_plate" %></span></div>
        <div>Day 9 <span><%= link_to "Drag Graphic", controller: "static_pages", action: "number", file_id: "drag_graphic" %></span></div>
        <div>Day 8 <span><%= link_to "US National flag", controller: "static_pages", action: "number", file_id: "us_national_flag" %></span></div>
        <div>Day 7 <span><%= link_to "Stopwatch", controller: "static_pages", action: "number", file_id: "stopwatch" %></span></div>
        <div>Day 6 <span><%= link_to "Blog", controller: "posts" %></span></div>
        <div>Day 5 <span><%= link_to "Have the time", controller: "static_pages", action: "number", file_id: "have_the_time" %></span></div>
        <div>Day 4 <span><%= link_to "Paint editor", controller: "static_pages", action: "number", file_id: "paint_editor" %></span></div>
        <div>Day 3 <span><%= link_to "Change the color", controller: "static_pages", action: "number", file_id: "change_the_color" %></span></div>
        <div>Day 2 <span><%= link_to "Draw the wall", controller: "static_pages", action: "number", file_id: "draw_the_wall" %></span></div>
        <div>Day 1 <span><%= link_to "Homepage", root_path %></span></div>
      </div>
    </div>
  </div>

app/views/static_pages/scraping.html.erb
<% provide(:title,"Scraping") %>
  <div class="container">
    <!-- 見出し -->
    <div class="jumbotron">
      <h1>Welcome!</h1>
      <h2 style="font-family:futura; font-weight:900">Scraping</h2>
      <hr>
        <p><strong>Naverまとめ トップ<%= @url_scrapings.length %></strong>
          <ul>
            <% @url_scrapings.each do |url_scraping| %>
              <li><%= link_to url_scraping[0], url_scraping[1] %></li>
            <% end %>        
          </ul>
        </p>
      <hr>

    </div><!-- 見出し終了 -->
  </div>